BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        Label:
            text: '34'
            halign: 'left'
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.25
            Button:
                text: 'up'
            Button:
                text: 'down'

    Label:
        text: 'Convert miles to km'
    Label:
        id: output_label
        text: "54.717"
        font_sizeL: 48
        color: (1, 1, 0, 1)